version: '3.8'

services:
  auramarket:
    build:
      context: .
      dockerfile: Dockerfile
    image: auramarket-frontend:latest
    container_name: auramarket_app
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME:-root}:${MONGO_INITDB_ROOT_PASSWORD:-example}@mongodb:27017/auramarket?authSource=admin
      - VITE_BACKEND_API_URL=http://localhost:8000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: auramarket-backend:latest
    container_name: auramarket_backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME:-root}:${MONGO_INITDB_ROOT_PASSWORD:-example}@mongodb:27017/auramarket?authSource=admin

  mongodb:
    image: mongo:latest
    container_name: auramarket_db
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-example}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

